# Generated by Django 3.2.16 on 2024-09-23 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'following')},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['user', 'following'], name='posts_follo_user_id_4b6ca6_idx'),
        ),
    ]
